info:
  contact: {}
paths:
  /v1/user/login:
    post:
      responses:
        "200":
          description: OK
          schema:
            type: String
        "400":
          description: Bad Request
          schema:
            type: String
        "401":
          description: Unauthorized
          schema:
            type: String
        "500":
          description: Internal Server Error
          schema:
            type: String
      summary: Login User
      tags:
      - user
swagger: "2.0"
